export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";

export const CREATE_PEOPLE = "CREATE_PEOPLE";
export const RETRIEVE_PEOPLES = "RETRIEVE_PEOPLES";
export const UPDATE_PEOPLE = "UPDATE_PEOPLE";
export const DELETE_PEOPLE = "DELETE_PEOPLE";